top_srcdir   = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
top_builddir = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
srcdir       = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules/metadata
builddir     = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules/metadata
VPATH        = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules/metadata

include $(top_srcdir)/build/special.mk

