top_srcdir   = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
top_builddir = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
srcdir       = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules/loggers
builddir     = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules/loggers
VPATH        = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules/loggers

include $(top_srcdir)/build/special.mk

