top_srcdir   = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
top_builddir = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
srcdir       = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules
builddir     = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules
VPATH        = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

