top_srcdir   = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
top_builddir = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
srcdir       = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules/echo
builddir     = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules/echo
VPATH        = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/modules/echo

include $(top_srcdir)/build/special.mk

