top_srcdir   = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
top_builddir = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
srcdir       = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/server/mpm
builddir     = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/server/mpm
VPATH        = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
