top_srcdir   = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
top_builddir = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
srcdir       = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/os/unix
builddir     = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/os/unix
VPATH        = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
