top_srcdir   = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
top_builddir = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
srcdir       = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/os
builddir     = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/os
VPATH        = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
