top_srcdir   = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
top_builddir = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20
srcdir       = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/server/mpm/prefork
builddir     = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/server/mpm/prefork
VPATH        = /home/bogdan/GWFax/faxgwiseWeb_NEW/httpd-2.2.20/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
